### PR TITLE
Fix allowlist for local subnets

### LINKED ISSUE #406: 3.18.1 - Private subnet in allowlist not working, lan-discovery works OK
Hi!  I'm using NordVPN version 3.18.1 on Linux Mint 21.3.  I seem to have an issue accessing LAN devices when a private subnet is added to the allowlist.  I do not have the same issue with any prior NordVPN versions including 3.18.0.

After clearing the allowlist and enabling "lan-discovery" my LAN devices are accessible, so I will continue to use lan-discovery for now. Thanks!

Steps to reproduce:

- nordvpn allowlist add subnet 192.168.1.0/24
- ping another LAN device eg. 192.168.1.99 = fail
- nordvpn allowlist remove all
- nordvpn set lan-discovery enabled
- ping another LAN device 192.168.1.99 = OK

```
$ nordvpn --version
NordVPN Version 3.18.1

$ nordvpn status
Status: Connected
Server: United States #6301
Hostname: us6301.nordvpn.com
IP: 172.93.177.235
Country: United States
City: Chicago
Current technology: NORDLYNX
Current protocol: UDP
Transfer: 169.76 KiB received, 363.82 KiB sent
Uptime: 10 minutes 33 seconds

$ nordvpn settings
Technology: NORDLYNX
Firewall: enabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: enabled
Kill Switch: enabled
Threat Protection Lite: disabled
Notify: disabled
Auto-connect: disabled
IPv6: disabled
Meshnet: disabled
DNS: disabled
LAN Discovery: disabled

$ nordvpn allowlist add subnet 192.168.1.0/24
Subnet 192.168.1.0/24 is allowlisted successfully.

$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -s 192.168.1.0/24 -i eno1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m comment --comment nordvpn -j DROP
-A OUTPUT -d 192.168.1.0/24 -o eno1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m mark --mark 0xe1f1 -m comment --comment nordvpn -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -o eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m comment --comment nordvpn -j DROP

$ nordvpn settings
Technology: NORDLYNX
Firewall: enabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: enabled
Kill Switch: enabled
Threat Protection Lite: disabled
Notify: disabled
Auto-connect: disabled
IPv6: disabled
Meshnet: disabled
DNS: disabled
LAN Discovery: disabled
Allowlisted subnets:
	192.168.1.0/24

$ ping -c3 192.168.1.99
PING 192.168.1.99 (192.168.1.99) 56(84) bytes of data.
--- 192.168.1.99 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2041ms

$ nordvpn allowlist remove all
All ports and subnets have been removed from the allowlist successfully.

$ nordvpn set lan-discovery enabled
LAN Discovery is set to 'enabled' successfully.

$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -s 169.254.0.0/16 -i eno1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -s 192.168.0.0/16 -i eno1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -s 172.16.0.0/12 -i eno1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -s 10.0.0.0/8 -i eno1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m comment --comment nordvpn -j DROP
-A OUTPUT -d 169.254.0.0/16 -o eno1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -d 192.168.0.0/16 -o eno1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -d 172.16.0.0/12 -o eno1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -d 10.0.0.0/8 -o eno1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m mark --mark 0xe1f1 -m comment --comment nordvpn -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -o eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m comment --comment nordvpn -j DROP

$ nordvpn settings
Technology: NORDLYNX
Firewall: enabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: enabled
Kill Switch: enabled
Threat Protection Lite: disabled
Notify: disabled
Auto-connect: disabled
IPv6: disabled
Meshnet: disabled
DNS: disabled
LAN Discovery: enabled

$ ping -c3 192.168.1.99
PING 192.168.1.99 (192.168.1.99) 56(84) bytes of data.
64 bytes from 192.168.1.99: icmp_seq=1 ttl=64 time=0.224 ms
64 bytes from 192.168.1.99: icmp_seq=2 ttl=64 time=0.274 ms
64 bytes from 192.168.1.99: icmp_seq=3 ttl=64 time=0.187 ms

--- 192.168.1.99 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2026ms
rtt min/avg/max/mdev = 0.187/0.228/0.274/0.035 ms

```

### PR DESCRIPTION
**Pull request by Savolro**
Fixes #406

### CODE REVIEW

File: daemon/routes/netlink/netlink.go [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+		netlinkRoute := toNetlinkRoute(route)
+		exists, err := routeExists(netlinkRoute)
+		if err != nil {
+			return fmt.Errorf("retrieving route %+v: %w", route, err)
+		}
+		if !exists {
+			return fmt.Errorf("route %+v does not exist", route)
+		}
+		if err := netlink.RouteDel(&netlinkRoute); err != nil {
+			return fmt.Errorf("deleting route %+v: %w", route, err)
```
Comment (bartoszWojciechO) [inline daemon/routes/netlink/netlink.go:71]: In case of errors in cases such as this(cleanup in a loop), perhaps it would be better to log an error but attempt continue with the cleanup? It might be possible to remove other rules.

File: daemon/routes/netlink/retriever.go [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+
+	links, err := netlink.LinkList()
+	if err != nil {
+		return nil, fmt.Errorf("listing links: %w", err)
+	}
+
+	return orderRoutesByRules(rules, routes, links), nil
+}
+
+// orderRoutesByRules groups routes by the rules that apply to the r
```
Comment (bartoszWojciechO) [inline daemon/routes/netlink/retriever.go:79]: Typo?

File: daemon/routes/netlink/netlink.go (hunk 1 above)
Comment (Savolro) [reply daemon/routes/netlink/netlink.go]: In most cases flush error is already just printed. So I did the following:
1. Cleanup is resumed after error, all errors are gathered and joined with `errors.Join`
2. Changed the remaining places of flush usage to log the warning

**Review by bartoszWojciechO — APPROVED** [review]

File: daemon/routes/netlink/netlink.go [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+		bits = net.IPv6len * 8
+	}
+	return &net.IPNet{
+		IP:   addr.AsSlice(),
+		Mask: net.CIDRMask(prefix.Bits(), bits),
+	}
+}
+
+// toNetlinkFamily converts bool to integer, representing netlink family.
+func toNetlinkFamily(val bool) int {
```
[the remark this answers is not in the document]
Comment (Savolro) [reply daemon/routes/netlink/netlink.go]: Kept the name but changed parameter type to `net.IP` so it should be more descriptive
https://github.com/NordSecurity/nordvpn-linux/pull/413/commits/3bc5a380a0b5984d5f7e9864e09338b587e8b00c#diff-d03f5db642c62b1a9719f70bdee3f89a9de88fe2d39537249b33fef4ecea1bb6R163

**Review by mariusSincovici — APPROVED** [review]

File: daemon/routes/netlink/netlink.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (mariusSincovici) [reply daemon/routes/netlink/netlink.go]: that's even nicer :smile:
